tv_grab_klive 하나의 url의 경우 예전대로
- 바이너리 의존성(xml_grep)을 가능한한 낮추도록
- 필요없는 권한 init.d 제거

diff --git a/root/usr/bin/tv_grab_klive b/root/usr/bin/tv_grab_klive
--- a/root/usr/bin/tv_grab_klive
+++ b/root/usr/bin/tv_grab_klive
@@ -1,7 +1,7 @@
 #!/bin/sh
 # tv_grab_file for getting your own xmltv
 DESC="KLIVE EPG GRABBER"
-VER="1.2"
+VER="1.3"
 CAP="baseline"
 
 for arg
@@ -24,9 +24,24 @@ fi
 
 args="${args:1:${#args}}"
 
+urls=$(echo $args | sed "s/|/ /g")
+nurl=$(echo $urls | wc -w)
+if [ $nurl -eq 1 ]; then
+  wget -q -O /epg2xml/klive.xml "${args}"
+  if [ $? -ne 0 ]; then
+    echo "ERROR: Invalid download url for xmltv"
+    echo "ERROR: ${args}"
+    exit 2
+  else
+    cat /epg2xml/klive.xml
+  fi
+
+  exit 0
+fi
+
 i=0
 gen_info=''
-for url in $(echo $args | sed "s/|/ /g")
+for url in $urls
 do
   xmltv_path="/epg2xml/klive-${i}.xml"
   wget -q -O "${xmltv_path}" "${url}"
